// // 1° Versão \\
// import Head from "next/head";
// import styles from "@/styles/Home.module.css";
// // @ts-ignore
// import {Splide, SplideSlide} from "@splidejs/react-splide";
// import'@splidejs/react-splide/css'; // <= importa o css padrão do splide


// export default function Home() {
//   return (
//     <>
//       <Head>
//         <title>Splide Js Demo</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <div className={styles.page}>
//         <main className={styles.main}>
//           <Splide options={{ type: 'loop' }}>{/* options={{ type: 'loop' }} => coloca um loop no container principal */}
//             <SplideSlide className={styles.item1}>
              
//             </SplideSlide>
//             <SplideSlide className={styles.item2}>
              
//             </SplideSlide>
//             <SplideSlide className={styles.item3}>
              
//             </SplideSlide>
//           </Splide>
//         </main>
//       </div>
//     </>
//   );
// }
//################################################################################################\\

// 2° Versão \\
// import Head from "next/head";
// import styles from "@/styles/Home.module.css";
// // @ts-ignore
// import {Splide, SplideSlide} from "@splidejs/react-splide";
// import'@splidejs/react-splide/css/sea-green'; // <= importa o css sea-green do splide


// export default function Home() {
//   return (
//     <>
//       <Head>
//         <title>Splide Js Demo</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <div className={styles.page}>
//         <main className={styles.main}>
//           <Splide options={{ type: 'loop' }}>{/* options={{ type: 'loop' }} => coloca um loop no container principal */}
//             <SplideSlide className={styles.item1}>
              
//             </SplideSlide>
//             <SplideSlide className={styles.item2}>
              
//             </SplideSlide>
//             <SplideSlide className={styles.item3}>
              
//             </SplideSlide>
//           </Splide>
//         </main>
//       </div>
//     </>
//   );
// }
//################################################################################################\\


// // 3° Versão \\
// import Head from "next/head";
// import styles from "@/styles/Home.module.css";
// // @ts-ignore
// import {Splide, SplideSlide} from "@splidejs/react-splide";
// import'@splidejs/react-splide/css/skyblue'; // <= importa o css skyblue do splide para as setas do carrocel

// export default function Home() {
//   return (
//     <>
//       <Head>
//         <title>Splide Js Demo</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <div className={styles.page}>
//         <main className={styles.main}>
//           <Splide options={{ type: 'loop' }}>{/* options={{ type: 'loop' }} => coloca um loop no container principal */}
//             <SplideSlide className={styles.item1}>
              
//             </SplideSlide>
//             <SplideSlide className={styles.item2}>
              
//             </SplideSlide>
//             <SplideSlide className={styles.item3}>
              
//             </SplideSlide>
//           </Splide>
//         </main>
//       </div>
//     </>
//   );
// }
//################################################################################################\\


// 4° Versão \\
import Head from "next/head";
import styles from "@/styles/Home.module.css";
// @ts-ignore
import {Splide, SplideSlide} from "@splidejs/react-splide";
import'@splidejs/react-splide/css'; // <= importa o css padrão do splide
import Image from "next/image";


export default function Home() {
  return (
    <>
      <Head>
        <title>Splide Js Demo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.page}>
        <main className={styles.main}>
          <Splide options={{ type: 'loop' }}>{/* options={{ type: 'loop' }} => coloca um loop no container principal */}
            <SplideSlide className={styles.item1}>
              <Image alt="Foto de um Bolo" src="/image1.jpg" width={500} height={500}
              style={{ objectFit: "cover" }} />
              
            </SplideSlide>
            <SplideSlide className={styles.item2}>
            <Image alt="Foto de um Bolo" src="/image2.jpg" width={500} height={500} />
              
            </SplideSlide>
            <SplideSlide className={styles.item3}>
            <Image alt="Foto de um Bolo" src="/image3.jpg" width={500} height={500} />
              
            </SplideSlide>
          </Splide>
        </main>
      </div>
    </>
  );
}